// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConfigDialog: typeof import('./src/components/ConfigDialog.vue')['default']
    CtrlBar: typeof import('./src/components/CtrlBar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    LabelButton: typeof import('./src/components/base/LabelButton.vue')['default']
    RoundButton: typeof import('./src/components/base/RoundButton.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
  }
}
