// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CtrlBar: typeof import('./src/components/CtrlBar.vue')['default']
    LabelButton: typeof import('./src/components/base/LabelButton.vue')['default']
    RoundButton: typeof import('./src/components/base/RoundButton.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    VideoGroup: typeof import('./src/components/VideoGroup.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
  }
}
